//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoInformaticaForense_Argentieri.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgettoInformaticaForense_Argentieri.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione! L&apos;orario del PC potrebbe essere stato modificato oppure il server NTP non è raggiungibile.
        ///Per verificare eventuali modifiche all&apos;orario di sistema consultare la sezione &quot;MODIFICHE ALL&apos;ORA DI SISTEMA&quot;..
        /// </summary>
        public static string App_DateTime_Error_Message {
            get {
                return ResourceManager.GetString("App_DateTime_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Activities Inspector.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esportazione conclusa con successo..
        /// </summary>
        public static string ExportCommand_ExportComplete_Message {
            get {
                return ResourceManager.GetString("ExportCommand_ExportComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Programmi installati.
        /// </summary>
        public static string InstalledPrograms_FileName {
            get {
                return ResourceManager.GetString("InstalledPrograms_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accensione - Spegnimento.
        /// </summary>
        public static string Intervals_FileName {
            get {
                return ResourceManager.GetString("Intervals_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a REPORT.
        /// </summary>
        public static string MainWindow_Report_Button_Content {
            get {
                return ResourceManager.GetString("MainWindow_Report_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dispositivo.
        /// </summary>
        public static string MainWindow_Usb_DeviceName {
            get {
                return ResourceManager.GetString("MainWindow_Usb_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome macchina.
        /// </summary>
        public static string MainWindow_Usb_MachineName {
            get {
                return ResourceManager.GetString("MainWindow_Usb_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data inserimento.
        /// </summary>
        public static string MainWindow_Usb_PluggedTime {
            get {
                return ResourceManager.GetString("MainWindow_Usb_PluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data rimozione.
        /// </summary>
        public static string MainWindow_Usb_UnpluggedTime {
            get {
                return ResourceManager.GetString("MainWindow_Usb_UnpluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PROGRAMMI INSTALLATI.
        /// </summary>
        public static string MainWindow_ViewerMode_InstalledPrograms {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_InstalledPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PREFETCH.
        /// </summary>
        public static string MainWindow_ViewerMode_Prefetch {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Prefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FILE RECENTI.
        /// </summary>
        public static string MainWindow_ViewerMode_Recents {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LOGON/LOGOFF.
        /// </summary>
        public static string MainWindow_ViewerMode_Sessions {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SHELLBAGS.
        /// </summary>
        public static string MainWindow_ViewerMode_ShellBags {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_ShellBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MODIFICHE ALL&apos;ORA DI SISTEMA.
        /// </summary>
        public static string MainWindow_ViewerMode_SystemTimeChanged {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_SystemTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ACCENSIONE/SPEGNIMENTO.
        /// </summary>
        public static string MainWindow_ViewerMode_TimeIntervals {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_TimeIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PERIFERICHE USB.
        /// </summary>
        public static string MainWindow_ViewerMode_Usb {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Usb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esporta.
        /// </summary>
        public static string MainWindows_ExportCommand_Content {
            get {
                return ResourceManager.GetString("MainWindows_ExportCommand_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorgente.
        /// </summary>
        public static string MainWindows_InstallEntry_DataSource {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome file.
        /// </summary>
        public static string MainWindows_InstallEntry_FileName {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percorso.
        /// </summary>
        public static string MainWindows_InstallEntry_FullPath {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data.
        /// </summary>
        public static string MainWindows_InstallEntry_installDate {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_installDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca.
        /// </summary>
        public static string MainWindows_LoadCommand_Content {
            get {
                return ResourceManager.GetString("MainWindows_LoadCommand_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome file.
        /// </summary>
        public static string MainWindows_Prefetch_ExecutableFileName {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_ExecutableFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estensione.
        /// </summary>
        public static string MainWindows_Prefetch_Extension {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data ultima esecuzione.
        /// </summary>
        public static string MainWindows_Prefetch_LastRunTime {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorgente.
        /// </summary>
        public static string MainWindows_Prefetch_SourceFileName {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data.
        /// </summary>
        public static string MainWindows_RecentFolder_ActionTime {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_ActionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorgente.
        /// </summary>
        public static string MainWindows_RecentFolder_DataSource {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome file.
        /// </summary>
        public static string MainWindows_RecentFolder_FileName {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percorso .
        /// </summary>
        public static string MainWindows_RecentFolder_FullPath {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo di accesso.
        /// </summary>
        public static string MainWindows_Sessions_AccessType {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata.
        /// </summary>
        public static string MainWindows_Sessions_Duration {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dominio.
        /// </summary>
        public static string MainWindows_Sessions_Group {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ora di disconnessione.
        /// </summary>
        public static string MainWindows_Sessions_LogOffTime {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_LogOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ora di accesso.
        /// </summary>
        public static string MainWindows_Sessions_LogOnTime {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_LogOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome macchina.
        /// </summary>
        public static string MainWindows_Sessions_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo di rete.
        /// </summary>
        public static string MainWindows_Sessions_NetworkAddress {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utente.
        /// </summary>
        public static string MainWindows_Sessions_UserName {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percorso assoluto.
        /// </summary>
        public static string MainWindows_ShellBags_AbsolutePath {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_AbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data accesso.
        /// </summary>
        public static string MainWindows_ShellBags_AccessedDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_AccessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data di creazione.
        /// </summary>
        public static string MainWindows_ShellBags_CreationDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data ultima scrittura.
        /// </summary>
        public static string MainWindows_ShellBags_LastRegistryWriteDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_LastRegistryWriteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percorso nel registro.
        /// </summary>
        public static string MainWindows_ShellBags_RegistryPath {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dispositivo.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_DeviceName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ora evento.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_EventTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome macchina.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo orario.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_NewTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vecchio orario.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_OldTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_OldTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data inserimento.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_PluggedTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_PluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data rimozione.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_UnpluggedTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_UnpluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Account.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_UserName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata.
        /// </summary>
        public static string MainWindows_TimeIntervals_Duration {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spegnimento.
        /// </summary>
        public static string MainWindows_TimeIntervals_End {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome macchina.
        /// </summary>
        public static string MainWindows_TimeIntervals_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accensione.
        /// </summary>
        public static string MainWindows_TimeIntervals_Start {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prefetch.
        /// </summary>
        public static string Prefetch_FileName {
            get {
                return ResourceManager.GetString("Prefetch_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File recenti.
        /// </summary>
        public static string Recents_FileName {
            get {
                return ResourceManager.GetString("Recents_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione caso.
        /// </summary>
        public static string ReportWindow_Description_Group_Surname {
            get {
                return ResourceManager.GetString("ReportWindow_Description_Group_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PERIZIA.
        /// </summary>
        public static string ReportWindow_Expertise_Value {
            get {
                return ResourceManager.GetString("ReportWindow_Expertise_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genera report.
        /// </summary>
        public static string ReportWindow_GenerateReport_Button_Content {
            get {
                return ResourceManager.GetString("ReportWindow_GenerateReport_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Investigatore.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Header {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Name {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Qualifica.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Qualification {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Surname {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONSULENZA TECNICA D&apos;UFFICIO.
        /// </summary>
        public static string ReportWindow_OfficialTechnicalConsultancy_Value {
            get {
                return ResourceManager.GetString("ReportWindow_OfficialTechnicalConsultancy_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Altro:.
        /// </summary>
        public static string ReportWindow_Other_Value {
            get {
                return ResourceManager.GetString("ReportWindow_Other_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PARERE PRO VERITATE.
        /// </summary>
        public static string ReportWindow_ParereProveritate_Value {
            get {
                return ResourceManager.GetString("ReportWindow_ParereProveritate_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONSULENZA TECNICA DI PARTE.
        /// </summary>
        public static string ReportWindow_TechnicalConsultancy_Value {
            get {
                return ResourceManager.GetString("ReportWindow_TechnicalConsultancy_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Activities Inspector - Report.
        /// </summary>
        public static string ReportWindow_Title {
            get {
                return ResourceManager.GetString("ReportWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione completata con successo!.
        /// </summary>
        public static string ReportWindows_OperationComplete_Info {
            get {
                return ResourceManager.GetString("ReportWindows_OperationComplete_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Batch (4).
        /// </summary>
        public static string Sessions_AccessType_Batch {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il tipo di accesso batch viene utilizzato dai server batch, in cui i processi possono essere esecutori per conto di un utente senza l&apos;intervento diretto..
        /// </summary>
        public static string Sessions_AccessType_Batch_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Batch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cached Interactive (11).
        /// </summary>
        public static string Sessions_AccessType_CachedInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un utente ha eseguito l&apos;accesso al computer con credenziali di rete archiviate localmente nel computer. Il controller di dominio non è stato contattato per verificare le credenziali..
        /// </summary>
        public static string Sessions_AccessType_CachedInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cached Remote Interactive (12).
        /// </summary>
        public static string Sessions_AccessType_CachedRemoteInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedRemoteInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un utente ha eseguito l&apos;accesso a questo computer in remoto utilizzando Servizi terminal o Desktop remoto.. Viene utilizzato per il controllo interno..
        /// </summary>
        public static string Sessions_AccessType_CachedRemoteInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedRemoteInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cached Unlock (13).
        /// </summary>
        public static string Sessions_AccessType_CachedUnlock {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accesso workstation..
        /// </summary>
        public static string Sessions_AccessType_CachedUnlock_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedUnlock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Interactive (2).
        /// </summary>
        public static string Sessions_AccessType_Interactive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Interactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un utente ha eseguito l&apos;accesso al computer..
        /// </summary>
        public static string Sessions_AccessType_Interactive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Interactive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Network Cleartext (8).
        /// </summary>
        public static string Sessions_AccessType_NetworkCleartext {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NetworkCleartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un utente ha eseguito l&apos;accesso al computer dalla rete. La password dell&apos;utente è stata passata al pacchetto di autenticazione nel formato non crittografato. L&apos;autenticazione incorporata in pacchetto tutte le credenziali hash prima di inviarle attraverso la rete. Le credenziali non attraversano la rete in testo normale (detto anche testo non crittografato)..
        /// </summary>
        public static string Sessions_AccessType_NetworkClearText_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NetworkClearText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Credentials (9).
        /// </summary>
        public static string Sessions_AccessType_NewCredentials {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NewCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un chiamante ha clonato il token corrente e specificato nuove credenziali per le connessioni in uscita. La nuova sessione di accesso ha la stessa identità locale, ma utilizza credenziali diverse per altre connessioni di rete..
        /// </summary>
        public static string Sessions_AccessType_NewCredentials_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NewCredentials_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remote Interactive (10).
        /// </summary>
        public static string Sessions_AccessType_RemoteInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_RemoteInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un utente ha eseguito l&apos;accesso a questo computer in remoto utilizzando Servizi terminal o Desktop remoto..
        /// </summary>
        public static string Sessions_AccessType_RemoteInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_RemoteInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sessioni.
        /// </summary>
        public static string Sessions_FileName {
            get {
                return ResourceManager.GetString("Sessions_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ShellBags.
        /// </summary>
        public static string ShellBags_FileName {
            get {
                return ResourceManager.GetString("ShellBags_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifiche all&apos;ora di sistema.
        /// </summary>
        public static string SystemTimeChanged_FileName {
            get {
                return ResourceManager.GetString("SystemTimeChanged_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usb.
        /// </summary>
        public static string Usb_FileName {
            get {
                return ResourceManager.GetString("Usb_FileName", resourceCulture);
            }
        }
    }
}
